config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  get 'signup', to: 'users#new'
  
  resources :users, only: [:index, :show, :new, :create, :destroy]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :status, presence: true, length: { maximum: 10 }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
   has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
     email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
   private

  def login(email, password)
    @user =User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy] 
  before_action :require_user_logged_in, only: [:index, :show, :create, :destroy]
  before_action :correct_user, only: [:show, :update, :edit, :destroy]

  def index
     if logged_in?
      @user = current_user
      @task = current_user.tasks.build
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
     end
  end
  
  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'Task が正常に投稿されました'
      redirect_to @task
    else
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'Task が投稿されませんでした'
      render 'tasks/index'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render:edit
    end
  end

  def destroy
    @task.destroy

    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users =User.all.page(params[:page])
   
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user =User.new
  end

  def create
    @user =User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_tasks.each do |task| %>
        <li><%= task %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Tasklist</a>
      </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          
         <ul class="nav navbar-nav navbar-right">
           <% if logged_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
               <li><%= link_to 'My profile', user_path(current_user) %></li>
               <li role="separator" class="divider"></li>
               <li><%= link_to 'Logout',logout_path, method: :delete%></li>
              </ul>
            </li>
           <% else %>
            
             <li><%= link_to 'Signup', signup_path %></li>
             <li><%= link_to 'Login', login_path %></li>
             <% if logged_in? %>
             <li><%= link_to 'Logout', logout_path, method: :delete %></li>
             <% end %>
             <li><%= link_to  '新規タスクの投稿', new_user_path %></li>
          
            
           <% end %>
         </ul>
        </div>
      </div>
  </nav>
</header>

<% flash.each do |task_type,task| %>
<div class="alert alert-<%= task_type %>"><%= task %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    

    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
 <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :task, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  
    
  </div>
</div>

app/views/tasks/_tasks.html.erb
<ul class="media-list">
  <% tasks.each do |task| %>
    <% user = task.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= task.created_at %></span>
        </div>
        <div>
          <p><%= task.content %></p>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h1>id : <%= @task.id %> 編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>


 <% if @tasks.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>ステータス</th>
        <th>タスク</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.id, task %></td>
          <td><%= task.status %></td>
          <td><%= task.content %></td>
        </tr>
       <% end %>
 <% end %>
      
<% if logged_in? %> 
 <div class="row">
  <aside class="col-md-4">
  <%= form_for(@task) do |f| %>
   <div class="form-group">
     <p>task</p>
    <%= f.text_area :content, class: 'form-control', rows: 5 %>
   </div>
   <div class="form-group">
     <p>status</p>
    <%= f.text_area :status, class: 'form-control', rows: 5 %>
   </div>
    <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
<% end %> 
  </aside>
 <div class="col-xs-8">
 </div>
</div>
<% if logged_in? %>
       <p>ログイン完了ユーザ: <%= current_user.name %></p>
       <% else %>
       <div class="center jumbotron">
        <div class="text-center">
          <h1>Welcome to the Tasks</h1>
          <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
        </div>
       </div>
      <% end %>
      
    </tbody>
  </table>
  <div>
    <%= paginate @tasks %>
  </div>
<% end %>

<%= link_to '新規タスクの投稿', new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>status = <%= @task.id %>のタスク詳細ページ</h1>



<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>ステータス</th>
    <td><%= @task.status %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @task.content %></td>
  </tr>
</table>

<%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-default' %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
   

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>


    

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Microposts <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li><a href="#">Microposts</a></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
   
  </div>
</div>